/* ===========================================================================
   Compute Atlas — dataset
   ---------------------------------------------------------------------------
   Everything the app renders comes from this one object. Edit it freely, or
   export a JSON file with the same shape and load it with the "Load JSON"
   button in the app.

   nodes[]  : the labels that live on the sphere
   edges[]  : relations between labels (drawn as arcs / "transmission lines")
   series{} : numeric time series (stock, rental prices, ...) attached to nodes
   items[]  : the information feed (tweets, news, filings, notes), tagged with
              one or more node ids

   NOTE: the values below are ILLUSTRATIVE SAMPLE DATA meant to exercise the
   layout. Replace them with your own sourced data before using this for
   anything real.
   =========================================================================== */

window.ATLAS_DATA = {
  meta: {
    title: "Compute Atlas",
    subtitle: "GPUs · AI compute · data centers",
    updated: "2026-08-17",
    note: "Sample dataset — illustrative values, not verified market data."
  },

  /* label categories -> colors */
  types: {
    company:    { label: "Company",       color: "#4fc3ff" },
    chip:       { label: "Chip / GPU",    color: "#ffb648" },
    datacenter: { label: "Data center",   color: "#b085ff" },
    tech:       { label: "Component",     color: "#ff6fb5" },
    energy:     { label: "Power",         color: "#3fe0a0" }
  },

  /* ---------------------------------------------------------------- nodes */
  nodes: [
    /* --- companies --- */
    { id: "nvidia", name: "Nvidia", type: "company", weight: 10, series: ["nvda", "h100_rent"],
      summary: "Designs the GPUs, NVLink fabric and rack-scale systems that most frontier training runs on.",
      metrics: [["Role", "GPU + system design"], ["Key line", "Hopper → Blackwell → Rubin"], ["Foundry", "TSMC"]] },
    { id: "amd", name: "AMD", type: "company", weight: 8, series: ["amd"],
      summary: "Instinct accelerator line; the main merchant-silicon alternative to Nvidia for inference fleets.",
      metrics: [["Role", "GPU design"], ["Key line", "MI300X → MI355X"], ["Foundry", "TSMC"]] },
    { id: "intel", name: "Intel", type: "company", weight: 6,
      summary: "Gaudi accelerators plus a foundry business courting AI silicon customers.",
      metrics: [["Role", "Silicon + foundry"], ["Key line", "Gaudi 3"]] },
    { id: "tsmc", name: "TSMC", type: "company", weight: 9, series: ["tsm"],
      summary: "Manufactures nearly every leading-edge AI accelerator; CoWoS packaging is the throughput bottleneck.",
      metrics: [["Role", "Foundry"], ["Nodes", "N4 / N3 / N2"], ["Constraint", "CoWoS capacity"]] },
    { id: "samsung", name: "Samsung", type: "company", weight: 6,
      summary: "HBM supplier and foundry; the swing capacity in high-bandwidth memory.",
      metrics: [["Role", "Memory + foundry"]] },
    { id: "sk_hynix", name: "SK hynix", type: "company", weight: 7,
      summary: "Leading HBM vendor; allocation here effectively sets accelerator ship dates.",
      metrics: [["Role", "HBM memory"], ["Lead product", "HBM3E 12-hi"]] },
    { id: "micron", name: "Micron", type: "company", weight: 6, series: ["mu"],
      summary: "Third HBM source, ramping capacity aggressively into AI demand.",
      metrics: [["Role", "HBM + DRAM"]] },
    { id: "broadcom", name: "Broadcom", type: "company", weight: 7, series: ["avgo"],
      summary: "Co-designs custom accelerators (TPU, MTIA-class) and supplies the Tomahawk/Jericho switch silicon.",
      metrics: [["Role", "Custom ASIC + networking"]] },
    { id: "marvell", name: "Marvell", type: "company", weight: 5,
      summary: "Custom silicon and optical DSPs for hyperscale interconnect.",
      metrics: [["Role", "Custom ASIC + optics"]] },
    { id: "asml", name: "ASML", type: "company", weight: 6,
      summary: "Sole supplier of EUV lithography; upstream gate on every leading-edge node.",
      metrics: [["Role", "Litho equipment"]] },
    { id: "foxconn", name: "Foxconn", type: "company", weight: 5,
      summary: "Integrates GPU trays and full racks; a read on real rack output vs. announced orders.",
      metrics: [["Role", "Rack integration"]] },
    { id: "dell", name: "Dell", type: "company", weight: 5,
      summary: "Ships AI factory racks to enterprises and neoclouds.",
      metrics: [["Role", "OEM systems"]] },
    { id: "supermicro", name: "Supermicro", type: "company", weight: 5,
      summary: "Liquid-cooled GPU systems, heavily exposed to neocloud build cycles.",
      metrics: [["Role", "OEM systems"]] },
    { id: "vertiv", name: "Vertiv", type: "company", weight: 4,
      summary: "Power distribution and liquid cooling plant — the long-lead items in a GPU hall.",
      metrics: [["Role", "Power + cooling gear"]] },
    { id: "arista", name: "Arista", type: "company", weight: 4,
      summary: "Ethernet switching for scale-out AI back-end networks.",
      metrics: [["Role", "Networking"]] },
    { id: "crusoe", name: "Crusoe", type: "company", weight: 5,
      summary: "Builds and operates greenfield GPU campuses, including the Abilene site.",
      metrics: [["Role", "DC developer"]] },
    { id: "coreweave", name: "CoreWeave", type: "company", weight: 7,
      summary: "Neocloud renting GPU capacity under multi-year contracts to labs and hyperscalers.",
      metrics: [["Role", "GPU cloud"]] },
    { id: "microsoft", name: "Microsoft", type: "company", weight: 9,
      summary: "Azure AI fleet plus its own Fairwater-class campuses; both buyer and landlord of compute.",
      metrics: [["Role", "Hyperscaler"], ["Silicon", "Maia"]] },
    { id: "google", name: "Google", type: "company", weight: 9,
      summary: "Runs the largest non-Nvidia training fleet on its own TPUs.",
      metrics: [["Role", "Hyperscaler"], ["Silicon", "TPU"]] },
    { id: "amazon", name: "Amazon / AWS", type: "company", weight: 8,
      summary: "Trainium fleets plus Nvidia capacity; anchor investor in Anthropic.",
      metrics: [["Role", "Hyperscaler"], ["Silicon", "Trainium"]] },
    { id: "meta", name: "Meta", type: "company", weight: 8,
      summary: "Largest merchant-GPU buyer outside the clouds; building multi-GW campuses.",
      metrics: [["Role", "Lab + operator"], ["Silicon", "MTIA"]] },
    { id: "oracle", name: "Oracle", type: "company", weight: 7,
      summary: "OCI leases enormous GPU blocks, much of it contracted to a single customer.",
      metrics: [["Role", "Cloud"]] },
    { id: "openai", name: "OpenAI", type: "company", weight: 9,
      summary: "Largest single contracted consumer of training and inference capacity.",
      metrics: [["Role", "AI lab"]] },
    { id: "anthropic", name: "Anthropic", type: "company", weight: 7,
      summary: "Trains across Trainium and TPU fleets in addition to Nvidia capacity.",
      metrics: [["Role", "AI lab"]] },
    { id: "xai", name: "xAI", type: "company", weight: 8,
      summary: "Vertically integrated build-out in Memphis; famous for compressing DC schedules.",
      metrics: [["Role", "AI lab + operator"]] },
    { id: "tesla", name: "Tesla", type: "company", weight: 5,
      summary: "Megapack batteries buffer GPU-hall load swings; shares talent and suppliers with xAI.",
      metrics: [["Role", "Storage + AI"]] },

    /* --- chips --- */
    { id: "a100", name: "A100", type: "chip", weight: 4,
      summary: "Ampere-generation workhorse, now mostly inference and academic fleets.",
      metrics: [["Vendor", "Nvidia"], ["Memory", "40/80 GB HBM2e"]] },
    { id: "h100", name: "H100", type: "chip", weight: 9, series: ["h100_rent"],
      summary: "Hopper GPU that defined the 2023-25 build-out; still the pricing reference for rented compute.",
      metrics: [["Vendor", "Nvidia"], ["Memory", "80 GB HBM3"], ["Package", "CoWoS-S"]] },
    { id: "h200", name: "H200", type: "chip", weight: 6,
      summary: "Hopper refresh with HBM3E; a drop-in memory-bandwidth upgrade.",
      metrics: [["Vendor", "Nvidia"], ["Memory", "141 GB HBM3E"]] },
    { id: "b200", name: "B200", type: "chip", weight: 8, series: ["b200_rent"],
      summary: "Blackwell dual-die GPU; the unit of account for 2025-26 capacity.",
      metrics: [["Vendor", "Nvidia"], ["Memory", "192 GB HBM3E"]] },
    { id: "gb200", name: "GB200 NVL72", type: "chip", weight: 9, series: ["b200_rent"],
      summary: "72-GPU liquid-cooled rack treated as one big accelerator — the reason halls got wet.",
      metrics: [["Vendor", "Nvidia"], ["Rack power", "~120 kW"], ["Fabric", "NVLink 5"]] },
    { id: "gb300", name: "GB300", type: "chip", weight: 7,
      summary: "Blackwell Ultra rack refresh with more HBM and higher rack power.",
      metrics: [["Vendor", "Nvidia"]] },
    { id: "vera_rubin", name: "Vera Rubin", type: "chip", weight: 6,
      summary: "Next platform generation; site power and cooling designs are already sized for it.",
      metrics: [["Vendor", "Nvidia"], ["Memory", "HBM4"]] },
    { id: "mi300x", name: "MI300X", type: "chip", weight: 6,
      summary: "AMD's high-memory accelerator, popular for large-context inference.",
      metrics: [["Vendor", "AMD"], ["Memory", "192 GB HBM3"]] },
    { id: "mi355x", name: "MI355X", type: "chip", weight: 5,
      summary: "AMD's Blackwell-class answer, sold as rack-scale systems.",
      metrics: [["Vendor", "AMD"], ["Memory", "288 GB HBM3E"]] },
    { id: "tpu_ironwood", name: "TPU (Ironwood)", type: "chip", weight: 6,
      summary: "Google's inference-oriented TPU generation, deployed in very large pods.",
      metrics: [["Vendor", "Google"], ["Partner", "Broadcom"]] },
    { id: "trainium2", name: "Trainium2", type: "chip", weight: 6,
      summary: "AWS training silicon; the basis of the Rainier-class clusters.",
      metrics: [["Vendor", "AWS"], ["Partner", "Marvell / Alchip"]] },
    { id: "maia100", name: "Maia 100", type: "chip", weight: 4,
      summary: "Microsoft's in-house accelerator for first-party inference workloads.",
      metrics: [["Vendor", "Microsoft"]] },

    /* --- components / technology --- */
    { id: "hbm3e", name: "HBM3E", type: "tech", weight: 7,
      summary: "Stacked memory that gates accelerator output; allocation is negotiated a year ahead.",
      metrics: [["Suppliers", "SK hynix, Micron, Samsung"]] },
    { id: "hbm4", name: "HBM4", type: "tech", weight: 5,
      summary: "Next memory generation tied to the Rubin-class ramp.",
      metrics: [["Status", "Qualification"]] },
    { id: "cowos", name: "CoWoS packaging", type: "tech", weight: 7,
      summary: "TSMC advanced packaging; the single most-watched capacity number in the supply chain.",
      metrics: [["Owner", "TSMC"]] },
    { id: "nvlink", name: "NVLink / NVSwitch", type: "tech", weight: 6,
      summary: "Scale-up fabric that makes a rack behave like one accelerator.",
      metrics: [["Owner", "Nvidia"]] },
    { id: "infiniband", name: "InfiniBand", type: "tech", weight: 5,
      summary: "Scale-out fabric for training clusters; competing with tuned Ethernet.",
      metrics: [["Owner", "Nvidia (Quantum)"]] },
    { id: "ethernet_ai", name: "AI Ethernet", type: "tech", weight: 5,
      summary: "Spectrum-X / Tomahawk-based back-end networks favored by operators wanting a second source.",
      metrics: [["Vendors", "Broadcom, Arista, Nvidia"]] },
    { id: "liquid_cooling", name: "Liquid cooling", type: "tech", weight: 5,
      summary: "Direct-to-chip loops and CDUs; a hard prerequisite for 100 kW+ racks.",
      metrics: [["Vendors", "Vertiv, Boyd, CoolIT"]] },

    /* --- data centers --- */
    { id: "colossus1", name: "Colossus 1", type: "datacenter", weight: 8,
      summary: "Memphis GPU hall built at record speed; the template for lab-owned construction.",
      metrics: [["Operator", "xAI"], ["Site", "Memphis, TN"], ["Fleet", "Hopper-class"]] },
    { id: "colossus2", name: "Colossus 2", type: "datacenter", weight: 8,
      summary: "Second Memphis campus, sized around Blackwell racks and on-site generation.",
      metrics: [["Operator", "xAI"], ["Site", "Memphis, TN"], ["Fleet", "GB200 / GB300"]] },
    { id: "stargate_abilene", name: "Stargate Abilene", type: "datacenter", weight: 9,
      summary: "Multi-building Texas campus leased end-to-end to a single AI tenant.",
      metrics: [["Developer", "Crusoe"], ["Cloud", "Oracle"], ["Tenant", "OpenAI"]] },
    { id: "fairwater", name: "Fairwater", type: "datacenter", weight: 7,
      summary: "Microsoft's purpose-built AI campus design, networked to behave as one supercomputer.",
      metrics: [["Operator", "Microsoft"], ["Site", "Mt Pleasant, WI"]] },
    { id: "prometheus", name: "Prometheus", type: "datacenter", weight: 7,
      summary: "Meta's Ohio cluster, partly served by on-site gas generation.",
      metrics: [["Operator", "Meta"], ["Site", "New Albany, OH"]] },
    { id: "hyperion", name: "Hyperion", type: "datacenter", weight: 7,
      summary: "Meta's Louisiana multi-GW campus, phased over several years.",
      metrics: [["Operator", "Meta"], ["Site", "Richland Parish, LA"]] },
    { id: "rainier", name: "Project Rainier", type: "datacenter", weight: 7,
      summary: "AWS Trainium mega-cluster in Indiana dedicated to a single lab tenant.",
      metrics: [["Operator", "AWS"], ["Site", "New Carlisle, IN"], ["Tenant", "Anthropic"]] },
    { id: "cw_plano", name: "CoreWeave Plano", type: "datacenter", weight: 5,
      summary: "Leased neocloud hall in North Texas serving contracted GPU capacity.",
      metrics: [["Operator", "CoreWeave"], ["Site", "Plano, TX"]] },
    { id: "cbf_iowa", name: "Council Bluffs", type: "datacenter", weight: 5,
      summary: "Long-running Google campus, now heavily TPU-weighted.",
      metrics: [["Operator", "Google"], ["Site", "Council Bluffs, IA"]] },

    /* --- power --- */
    { id: "tva", name: "TVA", type: "energy", weight: 5,
      summary: "Utility serving the Memphis campuses; substation timelines drive ramp schedules.",
      metrics: [["Region", "Tennessee Valley"]] },
    { id: "ercot", name: "ERCOT / Oncor", type: "energy", weight: 5,
      summary: "Texas grid and delivery utility behind the Abilene and DFW build-outs.",
      metrics: [["Region", "Texas"]] },
    { id: "gas_turbines", name: "On-site gas turbines", type: "energy", weight: 5,
      summary: "Bridge generation that lets halls energize years before grid interconnect.",
      metrics: [["Vendors", "GE Vernova, Solar Turbines"]] },
    { id: "ge_vernova", name: "GE Vernova", type: "energy", weight: 5,
      summary: "Turbine supplier with multi-year backlogs; a hard limit on bridge power.",
      metrics: [["Role", "Turbines + grid gear"]] },
    { id: "megapack", name: "Tesla Megapack", type: "energy", weight: 5,
      summary: "Battery buffer that smooths the millisecond load swings of synchronized training jobs.",
      metrics: [["Role", "Storage"]] },
    { id: "bloom", name: "Bloom Energy", type: "energy", weight: 4,
      summary: "Fuel-cell power modules used as fast-deploy on-site generation.",
      metrics: [["Role", "Fuel cells"]] }
  ],

  /* ---------------------------------------------------------------- edges */
  edges: [
    ["nvidia", "h100", "designs & sells"],
    ["nvidia", "h200", "designs & sells"],
    ["nvidia", "b200", "designs & sells"],
    ["nvidia", "gb200", "designs & sells"],
    ["nvidia", "gb300", "designs & sells"],
    ["nvidia", "vera_rubin", "roadmap"],
    ["nvidia", "a100", "designs & sells"],
    ["nvidia", "nvlink", "owns"],
    ["nvidia", "infiniband", "owns"],
    ["nvidia", "ethernet_ai", "competes in"],
    ["nvidia", "tsmc", "foundry customer of"],
    ["nvidia", "cowos", "consumes"],
    ["nvidia", "sk_hynix", "buys HBM from"],
    ["nvidia", "micron", "buys HBM from"],
    ["nvidia", "samsung", "qualifies HBM from"],
    ["nvidia", "foxconn", "rack integration by"],
    ["nvidia", "dell", "channel partner"],
    ["nvidia", "supermicro", "channel partner"],
    ["nvidia", "coreweave", "supplies & invests"],
    ["nvidia", "microsoft", "supplies"],
    ["nvidia", "meta", "supplies"],
    ["nvidia", "xai", "supplies"],
    ["nvidia", "oracle", "supplies"],
    ["nvidia", "amazon", "supplies"],
    ["nvidia", "openai", "supplies & partners"],
    ["nvidia", "amd", "competes with"],

    ["amd", "mi300x", "designs & sells"],
    ["amd", "mi355x", "designs & sells"],
    ["amd", "tsmc", "foundry customer of"],
    ["amd", "hbm3e", "consumes"],
    ["amd", "openai", "supplies"],
    ["amd", "oracle", "supplies"],
    ["amd", "meta", "supplies"],
    ["amd", "ethernet_ai", "backs"],

    ["intel", "tsmc", "foundry customer of"],
    ["intel", "nvidia", "competes with"],

    ["tsmc", "cowos", "operates"],
    ["tsmc", "asml", "buys EUV from"],
    ["tsmc", "broadcom", "manufactures for"],
    ["tsmc", "marvell", "manufactures for"],
    ["tsmc", "samsung", "competes with"],

    ["sk_hynix", "hbm3e", "supplies"],
    ["micron", "hbm3e", "supplies"],
    ["samsung", "hbm3e", "supplies"],
    ["sk_hynix", "hbm4", "samples"],
    ["micron", "hbm4", "samples"],
    ["hbm3e", "h200", "inside"],
    ["hbm3e", "b200", "inside"],
    ["hbm3e", "gb200", "inside"],
    ["hbm3e", "mi355x", "inside"],
    ["hbm4", "vera_rubin", "inside"],
    ["cowos", "h100", "packages"],
    ["cowos", "b200", "packages"],
    ["cowos", "mi300x", "packages"],

    ["broadcom", "tpu_ironwood", "co-designs"],
    ["broadcom", "ethernet_ai", "supplies silicon"],
    ["broadcom", "openai", "custom silicon for"],
    ["marvell", "trainium2", "co-designs"],
    ["arista", "ethernet_ai", "builds switches"],
    ["arista", "meta", "supplies"],
    ["arista", "microsoft", "supplies"],

    ["google", "tpu_ironwood", "designs & operates"],
    ["google", "cbf_iowa", "operates"],
    ["google", "anthropic", "invests in & supplies"],
    ["google", "tsmc", "foundry customer of"],

    ["amazon", "trainium2", "designs & operates"],
    ["amazon", "rainier", "operates"],
    ["amazon", "anthropic", "invests in & supplies"],
    ["amazon", "nvidia", "buys from"],

    ["microsoft", "maia100", "designs"],
    ["microsoft", "fairwater", "operates"],
    ["microsoft", "openai", "partner & investor"],
    ["microsoft", "coreweave", "leases capacity from"],
    ["microsoft", "gb200", "deploys"],
    ["microsoft", "liquid_cooling", "deploys"],

    ["meta", "prometheus", "operates"],
    ["meta", "hyperion", "operates"],
    ["meta", "h100", "operates fleet of"],
    ["meta", "gb200", "deploys"],
    ["meta", "gas_turbines", "uses"],

    ["openai", "stargate_abilene", "anchor tenant"],
    ["openai", "oracle", "contracts capacity from"],
    ["openai", "coreweave", "contracts capacity from"],
    ["openai", "gb200", "trains on"],
    ["openai", "b200", "trains on"],

    ["anthropic", "trainium2", "trains on"],
    ["anthropic", "tpu_ironwood", "trains on"],
    ["anthropic", "rainier", "tenant of"],

    ["oracle", "stargate_abilene", "cloud operator at"],
    ["oracle", "gb200", "deploys"],
    ["oracle", "crusoe", "leases from"],

    ["crusoe", "stargate_abilene", "developer of"],
    ["crusoe", "ercot", "interconnects with"],
    ["crusoe", "gas_turbines", "uses"],

    ["coreweave", "cw_plano", "operates"],
    ["coreweave", "h100", "rents out"],
    ["coreweave", "gb200", "rents out"],
    ["coreweave", "dell", "buys systems from"],
    ["coreweave", "supermicro", "buys systems from"],

    ["xai", "colossus1", "operates"],
    ["xai", "colossus2", "operates"],
    ["xai", "h100", "operates fleet of"],
    ["xai", "gb200", "deploys"],
    ["xai", "gb300", "deploys"],
    ["xai", "tesla", "shares suppliers with"],
    ["xai", "nvidia", "customer of"],

    ["colossus1", "tva", "powered by"],
    ["colossus1", "megapack", "buffered by"],
    ["colossus1", "gas_turbines", "bridged by"],
    ["colossus1", "h100", "houses"],
    ["colossus2", "tva", "powered by"],
    ["colossus2", "megapack", "buffered by"],
    ["colossus2", "gb200", "houses"],
    ["colossus2", "gb300", "houses"],
    ["colossus2", "liquid_cooling", "requires"],

    ["stargate_abilene", "ercot", "powered by"],
    ["stargate_abilene", "gas_turbines", "bridged by"],
    ["stargate_abilene", "gb200", "houses"],
    ["stargate_abilene", "liquid_cooling", "requires"],
    ["stargate_abilene", "vertiv", "equipment from"],

    ["fairwater", "gb200", "houses"],
    ["fairwater", "liquid_cooling", "requires"],
    ["fairwater", "ethernet_ai", "networked with"],

    ["prometheus", "gas_turbines", "powered by"],
    ["prometheus", "gb200", "houses"],
    ["hyperion", "gb200", "houses"],
    ["hyperion", "gas_turbines", "bridged by"],

    ["rainier", "trainium2", "houses"],
    ["cw_plano", "gb200", "houses"],
    ["cw_plano", "ercot", "powered by"],
    ["cbf_iowa", "tpu_ironwood", "houses"],

    ["gas_turbines", "ge_vernova", "supplied by"],
    ["gas_turbines", "bloom", "alternative to"],
    ["megapack", "tesla", "made by"],
    ["vertiv", "liquid_cooling", "supplies"],
    ["vertiv", "gb200", "cools"],
    ["ge_vernova", "ercot", "grid equipment for"],
    ["bloom", "prometheus", "supplies"],

    ["gb200", "nvlink", "uses"],
    ["gb200", "liquid_cooling", "requires"],
    ["h100", "infiniband", "clustered with"],
    ["b200", "nvlink", "uses"],
    ["trainium2", "ethernet_ai", "clustered with"],
    ["tpu_ironwood", "ethernet_ai", "clustered with"],
    ["h100", "a100", "succeeds"],
    ["b200", "h100", "succeeds"],
    ["gb300", "gb200", "succeeds"],
    ["vera_rubin", "gb300", "succeeds"],
    ["mi355x", "mi300x", "succeeds"],
    ["foxconn", "gb200", "assembles"],
    ["dell", "gb200", "ships"],
    ["supermicro", "liquid_cooling", "ships"]
  ],

  /* --------------------------------------------------------------- series */
  /* monthly cadence; null = no data yet */
  series: {
    nvda:      { label: "NVDA share price", unit: "$", start: "2024-01", step: "month",
      values: [49,72,90,87,110,123,117,119,121,138,141,134,120,124,110,108,135,158,172,178,186,191,183,199,205,214,208,226,241,236,252,268] },
    amd:       { label: "AMD share price", unit: "$", start: "2024-01", step: "month",
      values: [165,180,196,158,167,159,138,148,157,152,140,121,112,104,99,102,115,138,152,166,161,175,183,190,178,188,196,205,199,212,220,228] },
    tsm:       { label: "TSM ADR", unit: "$", start: "2024-01", step: "month",
      values: [105,128,138,136,152,174,168,165,190,196,186,197,205,180,164,172,199,232,241,258,272,285,276,294,301,318,309,330,344,338,356,371] },
    avgo:      { label: "AVGO share price", unit: "$", start: "2024-01", step: "month",
      values: [111,127,133,131,138,162,152,158,171,177,166,180,190,175,168,181,204,232,245,260,255,271,283,296,288,305,317,330,322,341,355,368] },
    mu:        { label: "MU share price", unit: "$", start: "2024-01", step: "month",
      values: [85,94,118,113,131,138,105,98,102,101,95,86,92,88,84,90,105,122,131,140,152,148,161,173,168,180,192,205,198,212,224,236] },
    h100_rent: { label: "H100 rental", unit: "$/GPU-hr", start: "2024-01", step: "month",
      values: [4.2,4.1,3.95,3.8,3.6,3.4,3.1,2.95,2.8,2.7,2.6,2.55,2.5,2.45,2.4,2.35,2.3,2.28,2.25,2.2,2.15,2.1,2.05,2.02,1.99,1.95,1.92,1.9,1.88,1.85,1.83,1.8] },
    b200_rent: { label: "B200 rental", unit: "$/GPU-hr", start: "2024-01", step: "month",
      values: [null,null,null,null,null,null,null,null,null,null,null,null,8.5,8.2,7.9,7.6,7.2,6.9,6.7,6.5,6.3,6.1,5.95,5.8,5.65,5.5,5.4,5.3,5.2,5.1,5.0,4.9] }
  },

  /* ---------------------------------------------------------------- items */
  /* kind: tweet | news | filing | data | note */
  items: [
    { date: "2026-08-16", kind: "tweet", source: "@elonmusk",
      text: "Colossus 2 crossed another power milestone this week. More Megapacks on site to smooth the training load.",
      body: "Replies to the post put the new figure at roughly a third above the level reported at the start of the quarter, though nobody outside the operator has confirmed it.\n\nThe interesting detail is the storage build-out rather than the headline number. Synchronised training jobs swing a hall's draw by tens of megawatts within a second, which the utility will not absorb, so batteries sit between the GPUs and the grid and flatten the profile.\n\nWatch whether the turbine pads next to the second hall get filled: that would signal the bridge generation is being extended rather than retired.",
      tags: ["xai", "colossus2", "megapack", "tva"] },
    { date: "2026-08-15", kind: "news", source: "Reuters",
      title: "TSMC lifts advanced packaging capacity guidance again",
      text: "CoWoS output is now expected to roughly double year over year, easing the main constraint on Blackwell-class shipments.",
      body: "The foundry raised its advanced packaging outlook for the second time this year, citing new lines coming online ahead of schedule and better throughput on existing tools.\n\nPackaging, not wafer starts, has been the throttle on accelerator supply since the Hopper ramp. Each Blackwell-class part consumes substantially more interposer area than the generation before it, so capacity that doubles in square millimetres translates into rather less than double the units.\n\nManagement declined to break out allocation by customer, but the commentary on qualification timelines lines up with the memory suppliers' remarks about the next generation, suggesting the bottleneck is migrating from packaging back toward HBM stacking.",
      tags: ["tsmc", "cowos", "nvidia", "b200"] },
    { date: "2026-08-14", kind: "data", source: "Rental index",
      title: "H100 spot rental slips to $1.80/GPU-hr",
      text: "Hopper rentals keep grinding down as Blackwell racks absorb new training demand; long-term reserved pricing is flat.",
      body: "Spot pricing for on-demand H100 capacity is down roughly 57% from the January 2024 reference point and about 10% over the past six months.\n\nThe decline is almost entirely a spot-market phenomenon. Reserved multi-year pricing has barely moved, because the buyers signing those contracts are underwriting new construction rather than renting spare cycles.\n\nThe read-through is that Hopper is finishing its transition from a scarce training asset to an inference commodity. Operators who financed fleets at 2023 prices are increasingly repricing them against that curve.",
      tags: ["h100", "coreweave", "nvidia"] },
    { date: "2026-08-13", kind: "news", source: "Bloomberg",
      title: "Abilene campus energizes two more buildings",
      text: "Bridge turbines carry the load while the Oncor interconnect steps up in phases.",
      body: "Two additional buildings at the Texas campus have taken load, bringing the site closer to its first full phase.\n\nAs at most of this cycle's greenfield sites, on-site turbines are carrying the hall while the utility interconnect is delivered in stages. That sequencing is what lets a campus start earning before the grid connection exists, and it is also why turbine delivery slots now show up in construction schedules as a critical path item.\n\nThe developer has said the permanent interconnect steps up over several tranches, with the bridge generation staying in place as backup rather than being removed.",
      tags: ["stargate_abilene", "crusoe", "ercot", "gas_turbines", "openai"] },
    { date: "2026-08-12", kind: "tweet", source: "@dylan522p",
      text: "The binding constraint moved again: it is no longer HBM, it is 500 kV transformers and turbine slots.",
      body: "The thread argues that every constraint in this build-out gets solved in roughly eighteen months, and the interesting question is always which one is binding next.\n\nMemory was the answer for two years; packaging for one. Both are now expanding faster than demand for them. Grid equipment is not: large power transformers and utility-scale turbines have multi-year backlogs and no obvious way to add capacity quickly, because the supply base was sized for a world of flat electricity demand.\n\nThe implication for schedules is that announced megawatts and delivered megawatts will keep diverging, and the gap will show up as slipped phases rather than cancelled projects.",
      tags: ["hbm3e", "ge_vernova", "gas_turbines", "ercot"] },
    { date: "2026-08-11", kind: "filing", source: "10-Q",
      title: "CoreWeave discloses expanded contracted backlog",
      text: "Backlog is dominated by multi-year commitments from two hyperscale customers and one frontier lab.",
      body: "The quarterly filing shows remaining performance obligations up sharply, with the disclosure noting significant customer concentration.\n\nTwo customers account for the majority of contracted revenue. The filing repeats the risk-factor language about dependence on a small number of counterparties, and adds that capacity is generally built against a signed contract rather than speculatively.\n\nThe capital structure remains the thing to watch: much of the debt is secured against GPU fleets whose spot rental value declines faster than the contract terms imply.",
      tags: ["coreweave", "microsoft", "openai", "gb200"] },
    { date: "2026-08-10", kind: "news", source: "The Information",
      title: "Meta accelerates Hyperion phase two",
      text: "Additional GB200 halls pulled forward; on-site generation contracted ahead of the utility tie-in.",
      body: "People familiar with the schedule say the Louisiana campus has moved several halls forward by roughly two quarters.\n\nThe acceleration is being enabled by generation contracted directly by the operator, a pattern now common enough that on-site power is treated as part of the standard site package rather than an exception.\n\nThe later phases of the campus still depend on transmission upgrades that are outside the operator's control, so the pull-forward mainly compresses the early ramp rather than the completion date.",
      tags: ["meta", "hyperion", "gb200", "gas_turbines"] },
    { date: "2026-08-08", kind: "tweet", source: "@sama",
      text: "Compute is still the gating factor on everything we want to ship.",
      body: "Posted in reply to a question about release timing. No specifics on capacity or dates were given.\n\nThe remark is consistent with the pattern of capacity agreements signed over the past year, which span several clouds and more than one silicon vendor.",
      tags: ["openai", "stargate_abilene", "oracle"] },
    { date: "2026-08-07", kind: "data", source: "Supply chain check",
      title: "GB200 rack output run-rate improves",
      text: "Integrators report better first-pass yield on liquid-cooled trays after connector rework.",
      body: "Checks across integrators point to a meaningful improvement in first-pass yield on liquid-cooled compute trays, following a redesign of the quick-disconnect couplings that caused most of the early rework.\n\nRack-level integration, not chip supply, has been the practical limiter on deployments for several quarters. A rack contains thousands of connections that must hold coolant under pressure for years, and the failure modes only appear under load.\n\nIf the improvement holds for another quarter, delivered rack counts should start tracking closer to the vendor's shipment commentary.",
      tags: ["gb200", "foxconn", "liquid_cooling", "vertiv"] },
    { date: "2026-08-06", kind: "news", source: "CNBC",
      title: "SK hynix sells out HBM output for the next cycle",
      text: "Allocation talks for the following generation are already underway with the two largest accelerator vendors.",
      body: "The memory maker said its high-bandwidth output is effectively committed for the coming cycle, with negotiations for the following generation already in progress.\n\nHBM is sold on long-dated allocation agreements rather than spot, so a sold-out position is less a statement about current demand than about how far ahead accelerator vendors are willing to commit capital.\n\nThe competitive question is whether a third qualified source materially changes pricing. So far each additional supplier has been absorbed by demand growth rather than translating into looser terms for buyers.",
      tags: ["sk_hynix", "hbm3e", "hbm4", "nvidia", "amd"] },
    { date: "2026-08-05", kind: "note", source: "Field note",
      text: "Memphis: substation build visibly further along; two additional turbine pads poured next to the second hall.",
      body: "Drive-by observation, not confirmed by the operator.\n\nThe substation steelwork is up and transformers appear to be on site, which would fit the utility's stated timeline for phased service later this year. Two fresh turbine pads have been poured on the north side of the second hall.\n\nIf the pads get equipment, the bridge generation is being expanded rather than wound down, which would suggest the permanent interconnect is still the gating item.",
      tags: ["colossus2", "tva", "gas_turbines", "xai"] },
    { date: "2026-08-04", kind: "news", source: "WSJ",
      title: "Microsoft details next Fairwater site",
      text: "Design copies the Wisconsin campus almost exactly, networked so multiple buildings act as one cluster.",
      body: "The company published details of another campus built to the same template as its Wisconsin site, down to the cooling plant and building geometry.\n\nThe design point is that several buildings are stitched together with a flat back-end network so that a single training job can span the campus. That pushes the engineering difficulty out of the building and into the fabric and the scheduler.\n\nStandardising the design is also a supply chain decision: identical buildings mean identical long-lead orders, which is worth more than site-specific optimisation when transformers and chillers are the scarce inputs.",
      tags: ["microsoft", "fairwater", "gb200", "ethernet_ai"] },
    { date: "2026-08-03", kind: "tweet", source: "@amd",
      text: "MI355X racks are shipping to cloud partners this quarter.",
      body: "Company post confirming rack-level shipments to cloud partners, without volumes or named customers.\n\nSelling at rack scale rather than as boards is the notable part: it puts the vendor into the same integration and liquid-cooling business as its competitor, and makes deployments dependent on the same cooling supply chain.",
      tags: ["amd", "mi355x", "oracle", "hbm3e"] },
    { date: "2026-08-01", kind: "data", source: "Price series",
      title: "B200 rentals settle near $4.90/GPU-hr",
      text: "Blackwell pricing continues to converge toward the level where Hopper capacity gets retired from training duty.",
      body: "Blackwell on-demand pricing has come down roughly 42% since the first quotes appeared, and the rate of decline is slowing.\n\nThe ratio that matters is Blackwell price against Hopper price per unit of useful work. Once renting new silicon is cheaper per token than running the old fleet, Hopper capacity stops being used for training regardless of whether it is depreciated.\n\nOn current numbers that crossover has already happened for large training jobs and is close for high-throughput inference.",
      tags: ["b200", "gb200", "h100"] },
    { date: "2026-07-30", kind: "filing", source: "8-K",
      title: "Oracle signs additional multi-year capacity contract",
      text: "Remaining performance obligations rise sharply on a single-tenant AI agreement.",
      body: "The filing discloses another multi-year cloud agreement, adding materially to remaining performance obligations.\n\nAs with the prior agreements, revenue is recognised only as capacity is delivered, and delivery depends on construction and power schedules the company does not fully control. The obligations therefore say more about contracted intent than near-term revenue.\n\nCustomer concentration continues to increase, which the filing acknowledges in its risk factors.",
      tags: ["oracle", "openai", "stargate_abilene"] },
    { date: "2026-07-28", kind: "news", source: "Data Center Dynamics",
      title: "AWS expands Rainier campus footprint",
      text: "Two more buildings added to the Trainium cluster serving a single lab tenant.",
      body: "Permit filings show two additional buildings at the Indiana campus, extending a site already dedicated largely to custom silicon for one tenant.\n\nRunning a frontier lab's training on in-house accelerators is the strategic point of the site: it removes a merchant-silicon vendor from the cost structure, at the price of owning the software stack problem.\n\nThe expansion suggests the arrangement is working well enough to commit more capital to it.",
      tags: ["amazon", "rainier", "trainium2", "anthropic"] },
    { date: "2026-07-26", kind: "tweet", source: "@nvidia",
      text: "Vera Rubin platform on schedule; partners are already validating power and cooling envelopes.",
      tags: ["nvidia", "vera_rubin", "hbm4", "liquid_cooling"] },
    { date: "2026-07-24", kind: "news", source: "Nikkei",
      title: "Foxconn adds AI rack capacity in Texas",
      text: "New line dedicated to liquid-cooled rack integration for North American campuses.",
      tags: ["foxconn", "gb200", "nvidia", "liquid_cooling"] },
    { date: "2026-07-22", kind: "data", source: "Grid tracker",
      title: "ERCOT large-load queue keeps climbing",
      text: "Requested interconnect capacity in the DFW and Abilene areas again outpaces approvals.",
      tags: ["ercot", "stargate_abilene", "cw_plano"] },
    { date: "2026-07-20", kind: "news", source: "Reuters",
      title: "Google expands Ironwood TPU deployment",
      text: "Additional pods land in Iowa; external customers get larger reserved blocks.",
      tags: ["google", "tpu_ironwood", "cbf_iowa", "broadcom", "anthropic"] },
    { date: "2026-07-18", kind: "note", source: "Field note",
      text: "Abilene: crane count down, transformer yard full — reads like fit-out rather than shell construction now.",
      tags: ["stargate_abilene", "crusoe", "ge_vernova"] },
    { date: "2026-07-16", kind: "filing", source: "10-Q",
      title: "Micron raises HBM revenue outlook",
      text: "Management says next-cycle HBM supply is effectively committed.",
      tags: ["micron", "hbm3e", "hbm4"] },
    { date: "2026-07-14", kind: "tweet", source: "@ID_AA_Carmack",
      text: "Interconnect topology matters more than raw FLOPs for the jobs people actually run at this scale.",
      tags: ["nvlink", "infiniband", "ethernet_ai", "gb200"] },
    { date: "2026-07-12", kind: "news", source: "Barron's",
      title: "Broadcom custom silicon backlog widens",
      text: "Two additional accelerator programs enter production planning with hyperscale customers.",
      tags: ["broadcom", "tpu_ironwood", "openai", "tsmc"] },
    { date: "2026-07-10", kind: "data", source: "Fleet estimate",
      title: "Installed Blackwell-class racks pass a new threshold",
      text: "Estimated share of training FLOPs on Blackwell overtakes Hopper for the first time.",
      tags: ["gb200", "b200", "h100", "nvidia"] },
    { date: "2026-07-08", kind: "news", source: "Memphis Business Journal",
      title: "TVA approves additional service to Memphis campuses",
      text: "Phased delivery tied to substation completion later this year.",
      tags: ["tva", "colossus1", "colossus2", "xai"] },
    { date: "2026-07-05", kind: "tweet", source: "@vertiv",
      text: "Coolant distribution unit lead times improving as new plants come online.",
      tags: ["vertiv", "liquid_cooling", "gb200"] },
    { date: "2026-07-02", kind: "news", source: "Financial Times",
      title: "ASML books strong EUV demand from logic customers",
      text: "Advanced-node capex tied directly to accelerator roadmaps through 2028.",
      tags: ["asml", "tsmc", "nvidia"] },
    { date: "2026-06-28", kind: "note", source: "Analysis",
      text: "Rough rule of thumb holding up: one gigawatt of AI campus absorbs roughly the output of a full quarter of leading-edge packaging.",
      tags: ["cowos", "tsmc", "hyperion", "stargate_abilene"] },
    { date: "2026-06-24", kind: "news", source: "The Register",
      title: "Supermicro wins neocloud liquid-cooled order",
      text: "Deployment targets Texas halls already sized for high-density racks.",
      tags: ["supermicro", "coreweave", "cw_plano", "liquid_cooling"] },
    { date: "2026-06-20", kind: "filing", source: "10-K",
      title: "Nvidia flags supply concentration risk",
      text: "Filing reiterates dependence on a single foundry and a small set of memory suppliers.",
      tags: ["nvidia", "tsmc", "sk_hynix", "samsung", "micron"] },
    { date: "2026-06-15", kind: "data", source: "Price series",
      title: "HBM contract pricing firms again",
      text: "Buyers accept higher pricing to secure allocation for the next accelerator generation.",
      tags: ["hbm3e", "hbm4", "sk_hynix", "micron", "samsung"] },
    { date: "2026-06-10", kind: "news", source: "Bloomberg",
      title: "Tesla ships more Megapacks to AI campuses",
      text: "Storage increasingly specified as standard equipment for large GPU halls.",
      tags: ["tesla", "megapack", "colossus2", "xai"] },
    { date: "2026-06-05", kind: "tweet", source: "@arista",
      text: "Back-end AI Ethernet deployments now routinely span multiple buildings.",
      tags: ["arista", "ethernet_ai", "fairwater", "meta"] },
    { date: "2026-05-30", kind: "news", source: "Reuters",
      title: "Dell reports record AI server backlog",
      text: "Shipments weighted toward rack-scale liquid-cooled configurations.",
      tags: ["dell", "gb200", "coreweave"] },
    { date: "2026-05-22", kind: "news", source: "Data Center Frontier",
      title: "Bloom fuel cells deployed at Ohio campus",
      text: "Modules provide bridge power while gas turbines are commissioned.",
      tags: ["bloom", "prometheus", "meta", "gas_turbines"] },
    { date: "2026-05-14", kind: "data", source: "Fleet estimate",
      title: "Hopper fleet shifts to inference",
      text: "A growing share of H100 capacity is now serving inference rather than training.",
      tags: ["h100", "a100", "coreweave", "meta"] },
    { date: "2026-05-06", kind: "news", source: "SemiAnalysis",
      title: "Rack power envelopes climb again",
      text: "Next-generation designs push past current limits, forcing electrical redesign mid-build at several sites.",
      tags: ["gb300", "vera_rubin", "liquid_cooling", "vertiv"] },
    { date: "2026-04-28", kind: "tweet", source: "@xai",
      text: "Training run on the new cluster is live.",
      tags: ["xai", "colossus2", "gb300"] },
    { date: "2026-04-20", kind: "news", source: "WSJ",
      title: "OpenAI diversifies accelerator suppliers",
      text: "Capacity agreements now span multiple silicon vendors alongside a custom program.",
      tags: ["openai", "amd", "broadcom", "nvidia"] },
    { date: "2026-04-12", kind: "filing", source: "8-K",
      title: "Crusoe closes financing for additional buildings",
      text: "Proceeds earmarked for the next phase of the Texas campus.",
      tags: ["crusoe", "stargate_abilene", "oracle"] },
    { date: "2026-04-02", kind: "news", source: "Nikkei",
      title: "Samsung HBM qualification advances",
      text: "A second-source qualification would loosen the tightest link in the accelerator chain.",
      tags: ["samsung", "hbm3e", "nvidia"] },
    { date: "2026-03-25", kind: "note", source: "Analysis",
      text: "Watch the ratio of announced megawatts to delivered turbines — it has been the most reliable schedule predictor this cycle.",
      tags: ["gas_turbines", "ge_vernova", "hyperion", "colossus2"] },
    { date: "2026-03-18", kind: "news", source: "Reuters",
      title: "Anthropic expands multi-silicon training strategy",
      text: "Workloads split across Trainium and TPU fleets to hedge supply.",
      tags: ["anthropic", "trainium2", "tpu_ironwood", "rainier"] },
    { date: "2026-03-10", kind: "data", source: "Price series",
      title: "A100 rentals reach commodity levels",
      text: "Older fleets increasingly used for fine-tuning and batch inference.",
      tags: ["a100", "h100"] },
    { date: "2026-02-27", kind: "news", source: "CNBC",
      title: "Microsoft leases more third-party GPU capacity",
      text: "Neocloud contracts fill the gap while owned campuses finish construction.",
      tags: ["microsoft", "coreweave", "fairwater"] },
    { date: "2026-02-14", kind: "tweet", source: "@tsmc",
      text: "Advanced packaging expansion on track at multiple sites.",
      tags: ["tsmc", "cowos"] },
    { date: "2026-01-30", kind: "filing", source: "10-Q",
      title: "AMD reports higher data center GPU revenue",
      text: "Growth driven by inference deployments at two large customers.",
      tags: ["amd", "mi300x", "mi355x", "oracle", "meta"] },
    { date: "2026-01-15", kind: "news", source: "Bloomberg",
      title: "Meta's Prometheus reaches initial capacity",
      text: "First training jobs run while later phases remain under construction.",
      tags: ["meta", "prometheus", "gb200"] },
    { date: "2025-12-12", kind: "news", source: "Reuters",
      title: "Nvidia introduces the GB300 rack generation",
      text: "More memory per rack and higher power density than the prior platform.",
      tags: ["nvidia", "gb300", "hbm3e", "liquid_cooling"] },
    { date: "2025-11-20", kind: "note", source: "Field note",
      text: "Plano hall fully populated; roof chillers running at what looks like near-design load.",
      tags: ["cw_plano", "coreweave", "gb200", "ercot"] },
    { date: "2025-10-08", kind: "news", source: "The Information",
      title: "Stargate site count expands",
      text: "Additional locations enter site selection as the anchor tenant contracts more capacity.",
      tags: ["openai", "stargate_abilene", "oracle", "crusoe"] },
    { date: "2025-09-01", kind: "data", source: "Fleet estimate",
      title: "Memphis fleet estimated at Hopper-class scale",
      text: "Estimate based on rack counts, power draw and public statements.",
      tags: ["xai", "colossus1", "h100"] }
  ]
};
